use serde::{Deserialize, Serialize};

#[derive(Serialize, Deserialize, Debug, Clone, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct BasicJavaType {
  pub id: String,
  pub name: String,
  pub package_path: String,
  #[serde(rename = "type")]
  pub type_: String,
}

pub fn get_basic_java_types() -> Vec<BasicJavaType> {
  vec![
    BasicJavaType {
      id: "java.lang.String".into(),
      name: "String".into(),
      package_path: "java.lang".into(),
      type_: "String".into(),
    },
    BasicJavaType {
      id: "java.lang.Long".into(),
      name: "Long".into(),
      package_path: "java.lang".into(),
      type_: "Long".into(),
    },
    BasicJavaType {
      id: "java.lang.Integer".into(),
      name: "Integer".into(),
      package_path: "java.lang".into(),
      type_: "Integer".into(),
    },
    BasicJavaType {
      id: "java.lang.Boolean".into(),
      name: "Boolean".into(),
      package_path: "java.lang".into(),
      type_: "Boolean".into(),
    },
    BasicJavaType {
      id: "java.lang.Double".into(),
      name: "Double".into(),
      package_path: "java.lang".into(),
      type_: "Double".into(),
    },
    BasicJavaType {
      id: "java.math.BigDecimal".into(),
      name: "BigDecimal".into(),
      package_path: "java.math".into(),
      type_: "BigDecimal".into(),
    },
    BasicJavaType {
      id: "java.time.Instant".into(),
      name: "Instant".into(),
      package_path: "java.time".into(),
      type_: "Instant".into(),
    },
    BasicJavaType {
      id: "java.time.LocalDateTime".into(),
      name: "LocalDateTime".into(),
      package_path: "java.time".into(),
      type_: "LocalDateTime".into(),
    },
    BasicJavaType {
      id: "java.time.LocalDate".into(),
      name: "LocalDate".into(),
      package_path: "java.time".into(),
      type_: "LocalDate".into(),
    },
    BasicJavaType {
      id: "java.time.LocalTime".into(),
      name: "LocalTime".into(),
      package_path: "java.time".into(),
      type_: "LocalTime".into(),
    },
    BasicJavaType {
      id: "java.time.OffsetDateTime".into(),
      name: "OffsetDateTime".into(),
      package_path: "java.time".into(),
      type_: "OffsetDateTime".into(),
    },
    BasicJavaType {
      id: "java.time.OffsetTime".into(),
      name: "OffsetTime".into(),
      package_path: "java.time".into(),
      type_: "OffsetTime".into(),
    },
    BasicJavaType {
      id: "java.util.Date".into(),
      name: "Date (util)".into(),
      package_path: "java.util".into(),
      type_: "Date".into(),
    },
    BasicJavaType {
      id: "java.sql.Date".into(),
      name: "Date (sql)".into(),
      package_path: "java.sql".into(),
      type_: "Date".into(),
    },
    BasicJavaType {
      id: "java.sql.Time".into(),
      name: "Time".into(),
      package_path: "java.sql".into(),
      type_: "Time".into(),
    },
    BasicJavaType {
      id: "java.sql.Timestamp".into(),
      name: "Timestamp".into(),
      package_path: "java.sql".into(),
      type_: "Timestamp".into(),
    },
    BasicJavaType {
      id: "java.util.TimeZone".into(),
      name: "TimeZone".into(),
      package_path: "java.util".into(),
      type_: "TimeZone".into(),
    },
    BasicJavaType {
      id: "java.lang.Byte[]".into(),
      name: "Byte[]".into(),
      package_path: "java.lang".into(),
      type_: "Byte[]".into(),
    },
    BasicJavaType {
      id: "java.sql.Blob".into(),
      name: "Blob".into(),
      package_path: "java.sql".into(),
      type_: "Blob".into(),
    },
    BasicJavaType {
      id: "java.lang.Byte".into(),
      name: "Byte".into(),
      package_path: "java.lang".into(),
      type_: "Byte".into(),
    },
    BasicJavaType {
      id: "java.lang.Character".into(),
      name: "Character".into(),
      package_path: "java.lang".into(),
      type_: "Character".into(),
    },
    BasicJavaType {
      id: "java.lang.Short".into(),
      name: "Short".into(),
      package_path: "java.lang".into(),
      type_: "Short".into(),
    },
    BasicJavaType {
      id: "java.lang.Float".into(),
      name: "Float".into(),
      package_path: "java.lang".into(),
      type_: "Float".into(),
    },
    BasicJavaType {
      id: "java.math.BigInteger".into(),
      name: "BigInteger".into(),
      package_path: "java.math".into(),
      type_: "BigInteger".into(),
    },
    BasicJavaType {
      id: "java.net.URL".into(),
      name: "URL".into(),
      package_path: "java.net".into(),
      type_: "URL".into(),
    },
    BasicJavaType {
      id: "java.time.Duration".into(),
      name: "Duration".into(),
      package_path: "java.time".into(),
      type_: "Duration".into(),
    },
    BasicJavaType {
      id: "java.time.ZonedDateTime".into(),
      name: "ZonedDateTime".into(),
      package_path: "java.time".into(),
      type_: "ZonedDateTime".into(),
    },
    BasicJavaType {
      id: "java.util.Calendar".into(),
      name: "Calendar".into(),
      package_path: "java.util".into(),
      type_: "Calendar".into(),
    },
    BasicJavaType {
      id: "java.util.Locale".into(),
      name: "Locale".into(),
      package_path: "java.util".into(),
      type_: "Locale".into(),
    },
    BasicJavaType {
      id: "java.util.Currency".into(),
      name: "Currency".into(),
      package_path: "java.util".into(),
      type_: "Currency".into(),
    },
    BasicJavaType {
      id: "java.lang.Class".into(),
      name: "Class".into(),
      package_path: "java.lang".into(),
      type_: "Class".into(),
    },
    BasicJavaType {
      id: "java.util.UUID".into(),
      name: "UUID".into(),
      package_path: "java.util".into(),
      type_: "UUID".into(),
    },
    BasicJavaType {
      id: "java.lang.Character[]".into(),
      name: "Character[]".into(),
      package_path: "java.lang".into(),
      type_: "Character[]".into(),
    },
    BasicJavaType {
      id: "java.sql.Clob".into(),
      name: "Clob".into(),
      package_path: "java.sql".into(),
      type_: "Clob".into(),
    },
    BasicJavaType {
      id: "java.sql.NClob".into(),
      name: "NClob".into(),
      package_path: "java.sql".into(),
      type_: "NClob".into(),
    },
    BasicJavaType {
      id: "boolean".into(),
      name: "boolean".into(),
      package_path: "boolean".into(),
      type_: "boolean".into(),
    },
    BasicJavaType {
      id: "byte".into(),
      name: "byte".into(),
      package_path: "byte".into(),
      type_: "byte".into(),
    },
    BasicJavaType {
      id: "float".into(),
      name: "float".into(),
      package_path: "float".into(),
      type_: "float".into(),
    },
    BasicJavaType {
      id: "char".into(),
      name: "char".into(),
      package_path: "char".into(),
      type_: "char".into(),
    },
    BasicJavaType {
      id: "int".into(),
      name: "int".into(),
      package_path: "int".into(),
      type_: "int".into(),
    },
    BasicJavaType {
      id: "double".into(),
      name: "double".into(),
      package_path: "double".into(),
      type_: "double".into(),
    },
    BasicJavaType {
      id: "short".into(),
      name: "short".into(),
      package_path: "short".into(),
      type_: "short".into(),
    },
    BasicJavaType {
      id: "long".into(),
      name: "long".into(),
      package_path: "long".into(),
      type_: "long".into(),
    },
    BasicJavaType {
      id: "byte[]".into(),
      name: "byte[]".into(),
      package_path: "byte[]".into(),
      type_: "byte[]".into(),
    },
    BasicJavaType {
      id: "char[]".into(),
      name: "char[]".into(),
      package_path: "char[]".into(),
      type_: "char[]".into(),
    },
    BasicJavaType {
      id: "org.geolatte.geom.Geometry".into(),
      name: "Geometry (geolatte)".into(),
      package_path: "org.geolatte.geom".into(),
      type_: "Geometry".into(),
    },
    BasicJavaType {
      id: "com.vividsolutions.jts.geom.Geometry".into(),
      name: "Geometry (jts)".into(),
      package_path: "com.vividsolutions.jts.geom".into(),
      type_: "Geometry".into(),
    },
    BasicJavaType {
      id: "java.net.InetAddress".into(),
      name: "InetAddress".into(),
      package_path: "java.net".into(),
      type_: "InetAddress".into(),
    },
    BasicJavaType {
      id: "java.time.ZoneOffset".into(),
      name: "ZoneOffset".into(),
      package_path: "java.time".into(),
      type_: "ZoneOffset".into(),
    },
  ]
}
